capture label variable Birth_M "Birth month"
capture label variable Birth_MY "Birth date in month years"
capture label variable Birth_S "Birth season"
capture label variable Birth_SY "Birth date in season years (uses ym with December Winter = 5)"
capture label variable Birth_Y "Birth year"
capture label variable End_Flag "Truncation indicator for end date"
capture label variable End_Ind "Indicator for whether spell has ended"
capture label variable End_MY "End date in month years"
capture label variable End_Reason1 "Promoted"
capture label variable End_Reason10 "Look after other persons"
capture label variable End_Reason11 "Moved area"
capture label variable End_Reason2 "Left for better job"
capture label variable End_Reason3 "Made redundant"
capture label variable End_Reason4 "Dismissed/sacked"
capture label variable End_Reason5 "Temporary job ended"
capture label variable End_Reason6 "Took retirement"
capture label variable End_Reason7 "Health reasons"
capture label variable End_Reason8 "Left to have baby"
capture label variable End_Reason9 "Look after family"
capture label variable End_Reason97 "Other reasons"
capture label variable FTE_FIN_MY "Latest plausible date left full-time education without gap"
capture label variable FTE_FIN_Source "Source variable (Further Education, School, or Life History)"
capture label variable FTE_IN_MY "Latest plausible date in full-time education without gap"
capture label variable FTE_IN_Source "Source variable (Further Education, School, or Life History)"
capture label variable FTE_NO_MY "Date no education recorded"
capture label variable FTE_NO_Source "Source variable (Further Education, School, or Life History)"
capture label variable FTE_Source "FTE_*_MY variable with data"
capture label variable hidp "Household Identifier"
capture label variable IntDate_M "Interview month"
capture label variable IntDate_MY "Interview date in month years - not necessarily correct for spell!"
capture label variable IntDate_S "Interview season"
capture label variable IntDate_SY "Interview date in season years (uses ym with December Winter = 5)"
capture label variable IntDate_Y "Interview year"
capture label variable ivfio "Interview Type"
capture label variable jbstat "Main activity at interview"
capture label variable Job_Attraction1 "Better money"
capture label variable Job_Attraction10 "Shorter/fewer hours"
capture label variable Job_Attraction11 "More flexible hours"
capture label variable Job_Attraction12 "Health reasons"
capture label variable Job_Attraction13 "Suits qualifications/training/experience"
capture label variable Job_Attraction14 "Less demanding"
capture label variable Job_Attraction15 "Prefer to previous job"
capture label variable Job_Attraction2 "Better career prospects"
capture label variable Job_Attraction3 "More responsibility"
capture label variable Job_Attraction4 "More secure job"
capture label variable Job_Attraction5 "More interesting work"
capture label variable Job_Attraction6 "Wanted specific type of job"
capture label variable Job_Attraction7 "To be own boss"
capture label variable Job_Attraction8 "Opportunities to use initiative"
capture label variable Job_Attraction9 "Nearer home/less travel"
capture label variable Job_Attraction97 "Other reason"
capture label variable Job_Change "Change of job since prior spell"
capture label variable Job_Hours "Part-time or full-time work"
capture label variable Last_IntDate_MY "Date of last recorded interview for participant"
capture label variable LB_M "Lower Bound month"
capture label variable LB_MY "Lower bound month-year"
capture label variable LB_S "Lower bound season"
capture label variable LB_SY "Lower bound season-year (uses ym with December Winter = 5)"
capture label variable LB_Y "Lower bound year"
capture label variable Next_ff_jbsemp "Fed-forward jbsemp at next recorded wave"
capture label variable Next_ff_jbstat "Fed-forward jbstat at next recorded wave"
capture label variable Next_Wave "Next recorded wave"
capture label variable pidp "Cross-wave person identifier"
capture label variable Prev_Job_Hours "Job hours from prior wave"
capture label variable Prev_Wave "Previous full wave"
capture label variable Source "Dataset(s) used to derive activity"
capture label variable Source_Type "Module used to derive activity"
capture label variable Source_Variable "Variable(s) used to derive activity"
capture label variable Start_Flag "Truncation indicator for start date"
capture label variable Start_MY "Start date in month years"
capture label variable Status "Economic activity"
capture label variable Status_Spells "Number of spells observation represents"
capture label variable Wave "Wave (= 18 + Wave for UKHLS)"

qui do "${do_fld}/Labels.do"
capture label values Start_Flag flag
capture label values End_Flag flag
capture label values End_Ind activity_ended_indicator
capture label values Job_Change job_change
capture label values Job_Hours job_hours
capture label values Source_Type source_type
capture label values Status status

